name: Compress Existing Images
on:
  workflow_dispatch: # This creates the manual "Play" button

jobs:
  build:
    name: Manual Image Optimization
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        id: compress-images
        uses: stellasoftio/image-optimizer-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jpeg-quality: 80
          compress-jpg: true

      - name: Commit Changes
        if: steps.compress-images.outputs.markdown_report != ''
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Fixed grain and optimized existing gallery images"
          git push
